### ISSUE TITLE
Reports Page

### ISSUE THREAD

**Issue by akissz** [ospiotr/disable-dashboard-for-woocommerce#16]
It seems there should be a option to disable Reports page due to the message on top of the page. (or maybe a setting to remove the words). Because there is already a option to remove Analytics so it seems both Analytics and Reports need option to remove.

"With the release of WooCommerce 4.0, these reports are being replaced. There is a new and better Analytics section available for users running WordPress 5.3+. Head on over to the WooCommerce Analytics or learn more about the new experience in the WooCommerce Analytics documentation."

**Comment by ospiotr** [comment]
Fixed in 2.5.0. Please update the plugin and let me know if everything is alright in your WooCommerce shop.
