### ISSUE TITLE
Bloat plugin bug maybe?

### ISSUE THREAD

**Issue by akissz** [ospiotr/disable-dashboard-for-woocommerce#18]
I see a problem with Bloat plugin maybe. When I activate the Bloat plugin I get errors. I can't give you much info because I'm doing a lot of beta testing of many things, plugins, themes, writing my own plugins and themes also. And also editing database manually for many things during this time. So its not a clean wordpress install, obviously. I notice this bug that maybe can be fixed on your end. (or maybe just needs clean wordpress install.) I will send you the error data so you can make that judgement. And reactivating or reinstalling Bloat plugin does not help. And reverting back to original wp themes do not help either.

This shows in the top area where normal php errors display:
**"Warning: in_array() expects parameter 2 to be array, bool given in ~/wordpress/wp-content/plugins/disable-dashboard-for-woocommerce/disable-dashboard-for-woocommerce.php on line 297"**

This shows in the area a little below that area:
**"The plugin generated 231 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin."**

**Comment by akissz** [comment]
Still having same issues, 
Warning: in_array() expects parameter 2 to be array, bool given in ~/wordpress/wp-content/plugins/disable-dashboard-for-woocommerce/disable-dashboard-for-woocommerce.php on line 297

**Comment by ospiotr** [comment]
Hi @akissz 
Please go to `wp-content/plugins` and check if you have `woocommerce` folder there.
Make sure that the folder name has not been modified.

**Comment by akissz** [comment]
Nothing is modified. I actually deleted both woocommerce and bloat plugin, and installed both fresh, last night. And this did not resolve the problem. It seems to be caused by more than what I have done alone.

**Comment by ospiotr** [comment]
dear @akissz , please send me your [WooCommerce system status](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/).

Thanks!

**Comment by akissz** [comment]
I see why the problem is happening. The active_plugins code you have is not the best in my opinion (this conflict does not break thousands of other plugins so it seems the code needs to be better.). The plugin is filter based. I don't think its necessary to have the active_plugins code in the checks (in the manner that you have it.) so there should maybe be an additional else code function... something..., to fix this bug on line 297. Also, have you thought about organizing the name better here and wordpress site. It seems a conflict. Its always difficult to find this github page using google. Maybe make the name be WooCommerce Bloat Disable and fix the directory also to be woocommerce-bloat-disable which would list correct with other woo dirs; instead of two names "Disable WooCommerce Bloat" and "disable dashboard for woocommerce"? Or add more links to the github from wp site. :)

**Comment by akissz** [comment]
The problem is the line 297 because my testing wp install stopped updating active_plugins table in the database. But as I write above I think the code can be improved to include functioning when these problems happen for other people. Only giving you ideas for the future. I'm not sure of a better code idea but I think one would be possible. Have a nice day :)

**Comment by ospiotr** [comment]
Hi @akissz 

Fixed in latest 2.5.3 version. Please update the plugin. Thank you for your time.
